version: '3'
services:

  ### Nginx container #########################################

  nginx:
      image: nginx:alpine
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      volumes:
        - /Users/smzdm/duanfuhao/smzdm_web:/etc/nginx/html/:rw
        - ./work/components/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./work/components/nginx/config/conf.d:/etc/nginx/conf.d:ro
        - ./work/components/nginx/log:/var/log/nginx:rw
      restart: always
      networks:
        - net-php

  ### PHP container #########################################

  php:
      build:
        context: ./build/php
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
          XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
          XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
      ports:
        - "${SWOOLE_PORT}:9501"
      expose:
        - "9000"
      volumes:
        - /Users/smzdm/duanfuhao/smzdm_web:/etc/nginx/html:rw
        - ./work/components/php/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./work/components/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./work/components/php/log:/var/log:rw
        - ./work/components/php/start.sh:/home/start.sh:rw
        - ./work/components/php/backup:/backup:rw
        - ./work/components/php/cron.d:/etc/cron.d:rw
      restart: always
      links:
        - mysql
        - redis
        - mysql:mysql_alias
        - redis:redis_alias
      networks:
        - net-php
        - net-mysql
        - net-redis

  ### GoLang container #########################################

  golang:
    build:
      context: ./build/golang/app
    ports:
      - "8010:8010"
    restart: always
    networks:
      - net-golang

  ### Mysql container #########################################

  mysql:
      image: mysql:5.6
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ./work/components/mysql/data:/var/lib/mysql:rw
        - ./work/components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - ./work/components/mysql/log:/var/log/mysql:rw
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - net-mysql

  ### Redis container #########################################

  redis:
      image: redis:4.0
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./work/components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./work/components/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      networks:
        - net-redis

  ### elasticsearch container #########################################

  elasticsearch: # 容器的名称 master
    image: elasticsearch:7.5.1  # 指定基于哪个镜像
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # JVM大小
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./work/components/elasticsearch/data:/usr/share/elasticsearch/data
      - ./work/components/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"    # 指定映射的端口
    networks:
      - net-es-kibana


### kibana container #########################################
  kibana:
    image: kibana:7.5.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - net-es-kibana

  ### elasticsearch-head plugin head #########################################
  elasticsearch-head:
    image: yanliangzhong/elasticsearch-head
    container_name: es-head
    restart: always
    ports:
      - "9100:9100"
    networks:
      - net-es-kibana

networks:
  net-php:
    driver: bridge
  net-mysql:
    driver: bridge
  net-redis:
    driver: bridge
  net-es-kibana:
    driver: bridge
  net-golang:
    driver: bridge