version: '3'
services:

  ### Nginx container #########################################

  nginx:
      image: nginx:alpine
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      volumes:
        - ./work/wwwroot:/etc/nginx/html/:rw
        - ./work/components/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./work/components/nginx/config/conf.d:/etc/nginx/conf.d:ro
        - ./work/components/nginx/log:/var/log/nginx:rw
      restart: always
      networks:
        - net-php72

  ### PHP container #########################################

  php72:
      build:
        context: ./build/php72
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
          XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
          XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
      ports:
        - "${SWOOLE_PORT}:9501"
      expose:
        - "9000"
      volumes:
        - ./work/wwwroot:/etc/nginx/html:rw
        - ./work/components/php72/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./work/components/php72/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./work/components/php72/log:/var/log:rw
        - ./work/components/php72/start.sh:/home/start.sh:rw
        - ./work/components/php72/backup:/backup:rw
        - ./work/components/php72/cron.d:/etc/cron.d:rw
      restart: always
      links:
        - mysql
        - redis
        - mysql:mysql_alias
        - redis:redis_alias
      networks:
        - net-php72
        - net-mysql
        - net-redis

  ### Mysql container #########################################

  mysql:
      image: mysql:5.6
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ./work/components/mysql/data:/var/lib/mysql:rw
        - ./work/components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - ./work/components/mysql/log:/var/log/mysql:rw
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - net-mysql

  ### Redis container #########################################

  redis:
      image: redis:4.0
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./work/components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./work/components/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      networks:
        - net-redis

  ### elasticsearch container #########################################

  elasticsearch: # 容器的名称 master
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0  # 指定基于哪个镜像
    container_name: elasticsearch
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # JVM大小
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./work/components/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ./work/components/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ./work/components/elasticsearch/log:/usr/share/elasticsearch/logs:rw
    ports:
      - "9200:9200"    # 指定映射的端口
      - "9300:9300"
    networks:
      - net-es-kibana

  ### elasticsearch2 container 创建es集群#########################################
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
  #   container_name: elasticsearch2
  #   restart: always
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./work/components/elasticsearch2/data:/usr/share/elasticsearch/data:rw
  #     - ./work/components/elasticsearch2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
  #     - ./work/components/elasticsearch2/log:/usr/share/elasticsearch/logs:rw
  #   ports:
  #   - "9201:9200"    # 指定映射的端口
  #   - "9301:9300"
  #   networks:
  #     - net-es-kibana

### kibana container #########################################
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - net-es-kibana

  ### elasticsearch-head plugin head #########################################
  elasticsearch-head:
    image: yanliangzhong/elasticsearch-head
    container_name: es-head
    restart: always
    ports:
      - "9100:9100"
    networks:
      - net-es-kibana

networks:
  net-php72:
  net-mysql:
  net-redis:
  net-es-kibana: